install:
	install -g root -o root main.py /usr/bin/lovi
	install -g root -o root -d /usr/share/applications
	install -g root -o root -m a+r,og+w lovi.desktop /usr/share/applications
	install -g root -o root -d /usr/share/icons
	install -g root -o root -m a+r,og+w lovi.png /usr/share/icons/lovi.png
